name: npm-publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run linter
        run: npm run lint

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Publish npm package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}